spring:
  cloud:
    gateway:
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true
      routes:
      - id: greeting-api
        uri: lb://GREETING-APPLICATION
        predicates:
        - Path=/greet
      - id: welcome-api
        uri: lb://WELCOME
        predicates:
        - Path=/welcome
  application:
    name: CLOUD-API-GATEWAY
server:
  port: 2222