spring:
  application:
    name: 'spring-batch'
  datasource:
    driver-class-name: org.h2.Driver
    password: kajol@123
    url: jdbc:h2:mem:testdb
    username: kajol
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
     
            